COMMIT  := $(shell git rev-parse --short HEAD)
VERSION := $(shell bun -e "console.log(require('./package.json').version)")

.DEFAULT_GOAL := dist

.PHONY: dist build-info

dist: build-info
	bun run build

build-info:
	@printf '// Auto-generated by Makefile — do not edit\nexport const COMMIT = "%s";\nexport const VERSION = "%s";\n' \
		"$(COMMIT)" "$(VERSION)" > src/build-info.ts
