export type Theme = {
  name: string;
  shikiTheme: string;
  mermaidTheme: "default" | "dark";
  variables: Record<string, string>;
};

const light: Theme = {
  name: "light",
  shikiTheme: "github-light",
  mermaidTheme: "default",
  variables: {
    "--bg": "#ffffff",
    "--fg": "#1a1a2e",
    "--h1-color": "#16213e",
    "--h2-color": "#0f3460",
    "--h3-color": "#555570",
    "--accent": "#0f3460",
    "--link": "#0f3460",
    "--link-hover": "#16213e",
    "--strong": "#16213e",
    "--em": "#555570",
    "--list-marker": "#0f3460",
    "--code-bg": "#f0f0f5",
    "--code-fg": "#1a1a2e",
    "--code-border": "#d0d0da",
    "--fence-bg": "#f0f0f5",
    "--fence-fg": "#1a1a2e",
    "--blockquote-border": "#0f3460",
    "--blockquote-fg": "#555570",
    "--table-border": "#d0d0da",
    "--table-header-bg": "#f0f0f5",
    "--hr-color": "#d0d0da",
    "--excalidraw-filter": "none",
  },
};

const dark: Theme = {
  name: "dark",
  shikiTheme: "github-dark",
  mermaidTheme: "dark",
  variables: {
    "--bg": "#1a1a2e",
    "--fg": "#e0e0e8",
    "--h1-color": "#e0e0e8",
    "--h2-color": "#7aa2f7",
    "--h3-color": "#9898b0",
    "--accent": "#7aa2f7",
    "--link": "#7aa2f7",
    "--link-hover": "#a5c0ff",
    "--strong": "#e8e8f0",
    "--em": "#9898b0",
    "--list-marker": "#7aa2f7",
    "--code-bg": "#24243e",
    "--code-fg": "#c0caf5",
    "--code-border": "#3b3b5c",
    "--fence-bg": "#24243e",
    "--fence-fg": "#c0caf5",
    "--blockquote-border": "#7aa2f7",
    "--blockquote-fg": "#9898b0",
    "--table-border": "#3b3b5c",
    "--table-header-bg": "#24243e",
    "--hr-color": "#3b3b5c",
    "--excalidraw-filter": "invert(1) hue-rotate(180deg)",
  },
};

// --- Catppuccin ---

const catppuccinLatte: Theme = {
  name: "catppuccin-latte",
  shikiTheme: "catppuccin-latte",
  mermaidTheme: "default",
  variables: {
    "--bg": "#eff1f5",
    "--fg": "#4c4f69",
    "--h1-color": "#8839ef",
    "--h2-color": "#1e66f5",
    "--h3-color": "#179299",
    "--accent": "#1e66f5",
    "--link": "#1e66f5",
    "--link-hover": "#7287fd",
    "--strong": "#4c4f69",
    "--em": "#7287fd",
    "--list-marker": "#8839ef",
    "--code-bg": "#e6e9ef",
    "--code-fg": "#40a02b",
    "--code-border": "#ccd0da",
    "--fence-bg": "#e6e9ef",
    "--fence-fg": "#4c4f69",
    "--blockquote-border": "#df8e1d",
    "--blockquote-fg": "#6c6f85",
    "--table-border": "#ccd0da",
    "--table-header-bg": "#e6e9ef",
    "--hr-color": "#ccd0da",
    "--excalidraw-filter": "none",
  },
};

const catppuccinFrappe: Theme = {
  name: "catppuccin-frappe",
  shikiTheme: "catppuccin-frappe",
  mermaidTheme: "dark",
  variables: {
    "--bg": "#303446",
    "--fg": "#c6d0f5",
    "--h1-color": "#ca9ee6",
    "--h2-color": "#8caaee",
    "--h3-color": "#81c8be",
    "--accent": "#8caaee",
    "--link": "#8caaee",
    "--link-hover": "#babbf1",
    "--strong": "#c6d0f5",
    "--em": "#babbf1",
    "--list-marker": "#ca9ee6",
    "--code-bg": "#414559",
    "--code-fg": "#a6d189",
    "--code-border": "#51576d",
    "--fence-bg": "#414559",
    "--fence-fg": "#c6d0f5",
    "--blockquote-border": "#e5c890",
    "--blockquote-fg": "#a5adce",
    "--table-border": "#51576d",
    "--table-header-bg": "#414559",
    "--hr-color": "#51576d",
    "--excalidraw-filter": "invert(1) hue-rotate(180deg)",
  },
};

const catppuccinMacchiato: Theme = {
  name: "catppuccin-macchiato",
  shikiTheme: "catppuccin-macchiato",
  mermaidTheme: "dark",
  variables: {
    "--bg": "#24273a",
    "--fg": "#cad3f5",
    "--h1-color": "#c6a0f6",
    "--h2-color": "#8aadf4",
    "--h3-color": "#8bd5ca",
    "--accent": "#8aadf4",
    "--link": "#8aadf4",
    "--link-hover": "#b7bdf8",
    "--strong": "#cad3f5",
    "--em": "#b7bdf8",
    "--list-marker": "#c6a0f6",
    "--code-bg": "#363a4f",
    "--code-fg": "#a6da95",
    "--code-border": "#494d64",
    "--fence-bg": "#363a4f",
    "--fence-fg": "#cad3f5",
    "--blockquote-border": "#eed49f",
    "--blockquote-fg": "#a5adcb",
    "--table-border": "#494d64",
    "--table-header-bg": "#363a4f",
    "--hr-color": "#494d64",
    "--excalidraw-filter": "invert(1) hue-rotate(180deg)",
  },
};

const catppuccinMocha: Theme = {
  name: "catppuccin-mocha",
  shikiTheme: "catppuccin-mocha",
  mermaidTheme: "dark",
  variables: {
    "--bg": "#1e1e2e",
    "--fg": "#cdd6f4",
    "--h1-color": "#cba6f7",
    "--h2-color": "#89b4fa",
    "--h3-color": "#94e2d5",
    "--accent": "#89b4fa",
    "--link": "#89b4fa",
    "--link-hover": "#b4befe",
    "--strong": "#cdd6f4",
    "--em": "#b4befe",
    "--list-marker": "#cba6f7",
    "--code-bg": "#313244",
    "--code-fg": "#a6e3a1",
    "--code-border": "#45475a",
    "--fence-bg": "#313244",
    "--fence-fg": "#cdd6f4",
    "--blockquote-border": "#f9e2af",
    "--blockquote-fg": "#a6adc8",
    "--table-border": "#45475a",
    "--table-header-bg": "#313244",
    "--hr-color": "#45475a",
    "--excalidraw-filter": "invert(1) hue-rotate(180deg)",
  },
};

// --- Monokai ---

const monokaiDark: Theme = {
  name: "monokai-dark",
  shikiTheme: "monokai",
  mermaidTheme: "dark",
  variables: {
    "--bg": "#272822",
    "--fg": "#f8f8f2",
    "--h1-color": "#f92672",
    "--h2-color": "#66d9ef",
    "--h3-color": "#ae81ff",
    "--accent": "#66d9ef",
    "--link": "#66d9ef",
    "--link-hover": "#a6e22e",
    "--strong": "#f8f8f2",
    "--em": "#e6db74",
    "--list-marker": "#fd971f",
    "--code-bg": "#3e3d32",
    "--code-fg": "#a6e22e",
    "--code-border": "#49483e",
    "--fence-bg": "#3e3d32",
    "--fence-fg": "#f8f8f2",
    "--blockquote-border": "#fd971f",
    "--blockquote-fg": "#75715e",
    "--table-border": "#49483e",
    "--table-header-bg": "#3e3d32",
    "--hr-color": "#49483e",
    "--excalidraw-filter": "invert(1) hue-rotate(180deg)",
  },
};

const monokaiLight: Theme = {
  name: "monokai-light",
  shikiTheme: "light-plus",
  mermaidTheme: "default",
  variables: {
    "--bg": "#fafafa",
    "--fg": "#49483e",
    "--h1-color": "#f92672",
    "--h2-color": "#0089b3",
    "--h3-color": "#7653c1",
    "--accent": "#0089b3",
    "--link": "#0089b3",
    "--link-hover": "#7a8a0e",
    "--strong": "#2e2e22",
    "--em": "#b58900",
    "--list-marker": "#d65d0e",
    "--code-bg": "#f0efe7",
    "--code-fg": "#7a8a0e",
    "--code-border": "#e0dfce",
    "--fence-bg": "#f0efe7",
    "--fence-fg": "#49483e",
    "--blockquote-border": "#d65d0e",
    "--blockquote-fg": "#75715e",
    "--table-border": "#e0dfce",
    "--table-header-bg": "#f0efe7",
    "--hr-color": "#e0dfce",
    "--excalidraw-filter": "none",
  },
};

// --- Gruvbox ---

const gruvboxDark: Theme = {
  name: "gruvbox-dark",
  shikiTheme: "gruvbox-dark-medium",
  mermaidTheme: "dark",
  variables: {
    "--bg": "#282828",
    "--fg": "#ebdbb2",
    "--h1-color": "#fabd2f",
    "--h2-color": "#83a598",
    "--h3-color": "#d3869b",
    "--accent": "#83a598",
    "--link": "#83a598",
    "--link-hover": "#8ec07c",
    "--strong": "#fbf1c7",
    "--em": "#b8bb26",
    "--list-marker": "#fe8019",
    "--code-bg": "#3c3836",
    "--code-fg": "#b8bb26",
    "--code-border": "#504945",
    "--fence-bg": "#3c3836",
    "--fence-fg": "#ebdbb2",
    "--blockquote-border": "#fe8019",
    "--blockquote-fg": "#a89984",
    "--table-border": "#504945",
    "--table-header-bg": "#3c3836",
    "--hr-color": "#504945",
    "--excalidraw-filter": "invert(1) hue-rotate(180deg)",
  },
};

const gruvboxLight: Theme = {
  name: "gruvbox-light",
  shikiTheme: "gruvbox-light-medium",
  mermaidTheme: "default",
  variables: {
    "--bg": "#fbf1c7",
    "--fg": "#3c3836",
    "--h1-color": "#b57614",
    "--h2-color": "#076678",
    "--h3-color": "#8f3f71",
    "--accent": "#076678",
    "--link": "#076678",
    "--link-hover": "#427b58",
    "--strong": "#282828",
    "--em": "#79740e",
    "--list-marker": "#af3a03",
    "--code-bg": "#ebdbb2",
    "--code-fg": "#79740e",
    "--code-border": "#d5c4a1",
    "--fence-bg": "#ebdbb2",
    "--fence-fg": "#3c3836",
    "--blockquote-border": "#af3a03",
    "--blockquote-fg": "#665c54",
    "--table-border": "#d5c4a1",
    "--table-header-bg": "#ebdbb2",
    "--hr-color": "#d5c4a1",
    "--excalidraw-filter": "none",
  },
};

// --- Nord ---

const nordDark: Theme = {
  name: "nord-dark",
  shikiTheme: "nord",
  mermaidTheme: "dark",
  variables: {
    "--bg": "#2e3440",
    "--fg": "#d8dee9",
    "--h1-color": "#88c0d0",
    "--h2-color": "#81a1c1",
    "--h3-color": "#b48ead",
    "--accent": "#81a1c1",
    "--link": "#81a1c1",
    "--link-hover": "#8fbcbb",
    "--strong": "#eceff4",
    "--em": "#ebcb8b",
    "--list-marker": "#d08770",
    "--code-bg": "#3b4252",
    "--code-fg": "#a3be8c",
    "--code-border": "#434c5e",
    "--fence-bg": "#3b4252",
    "--fence-fg": "#d8dee9",
    "--blockquote-border": "#d08770",
    "--blockquote-fg": "#9da7ba",
    "--table-border": "#434c5e",
    "--table-header-bg": "#3b4252",
    "--hr-color": "#434c5e",
    "--excalidraw-filter": "invert(1) hue-rotate(180deg)",
  },
};

const nordLight: Theme = {
  name: "nord-light",
  shikiTheme: "min-light",
  mermaidTheme: "default",
  variables: {
    "--bg": "#eceff4",
    "--fg": "#2e3440",
    "--h1-color": "#5e81ac",
    "--h2-color": "#81a1c1",
    "--h3-color": "#b48ead",
    "--accent": "#81a1c1",
    "--link": "#5e81ac",
    "--link-hover": "#8fbcbb",
    "--strong": "#2e3440",
    "--em": "#5e81ac",
    "--list-marker": "#d08770",
    "--code-bg": "#e5e9f0",
    "--code-fg": "#a3be8c",
    "--code-border": "#d8dee9",
    "--fence-bg": "#e5e9f0",
    "--fence-fg": "#2e3440",
    "--blockquote-border": "#d08770",
    "--blockquote-fg": "#4c566a",
    "--table-border": "#d8dee9",
    "--table-header-bg": "#e5e9f0",
    "--hr-color": "#d8dee9",
    "--excalidraw-filter": "none",
  },
};

// --- Solarized ---

const solarizedDark: Theme = {
  name: "solarized-dark",
  shikiTheme: "solarized-dark",
  mermaidTheme: "dark",
  variables: {
    "--bg": "#002b36",
    "--fg": "#839496",
    "--h1-color": "#268bd2",
    "--h2-color": "#2aa198",
    "--h3-color": "#6c71c4",
    "--accent": "#2aa198",
    "--link": "#268bd2",
    "--link-hover": "#2aa198",
    "--strong": "#93a1a1",
    "--em": "#b58900",
    "--list-marker": "#cb4b16",
    "--code-bg": "#073642",
    "--code-fg": "#859900",
    "--code-border": "#586e75",
    "--fence-bg": "#073642",
    "--fence-fg": "#839496",
    "--blockquote-border": "#cb4b16",
    "--blockquote-fg": "#657b83",
    "--table-border": "#586e75",
    "--table-header-bg": "#073642",
    "--hr-color": "#586e75",
    "--excalidraw-filter": "invert(1) hue-rotate(180deg)",
  },
};

const solarizedLight: Theme = {
  name: "solarized-light",
  shikiTheme: "solarized-light",
  mermaidTheme: "default",
  variables: {
    "--bg": "#fdf6e3",
    "--fg": "#657b83",
    "--h1-color": "#268bd2",
    "--h2-color": "#2aa198",
    "--h3-color": "#6c71c4",
    "--accent": "#2aa198",
    "--link": "#268bd2",
    "--link-hover": "#2aa198",
    "--strong": "#586e75",
    "--em": "#b58900",
    "--list-marker": "#cb4b16",
    "--code-bg": "#eee8d5",
    "--code-fg": "#859900",
    "--code-border": "#93a1a1",
    "--fence-bg": "#eee8d5",
    "--fence-fg": "#657b83",
    "--blockquote-border": "#cb4b16",
    "--blockquote-fg": "#586e75",
    "--table-border": "#93a1a1",
    "--table-header-bg": "#eee8d5",
    "--hr-color": "#93a1a1",
    "--excalidraw-filter": "none",
  },
};

export const themes: Record<string, Theme> = {
  light,
  dark,
  "catppuccin-latte": catppuccinLatte,
  "catppuccin-frappe": catppuccinFrappe,
  "catppuccin-macchiato": catppuccinMacchiato,
  "catppuccin-mocha": catppuccinMocha,
  "monokai-dark": monokaiDark,
  "monokai-light": monokaiLight,
  "gruvbox-dark": gruvboxDark,
  "gruvbox-light": gruvboxLight,
  "nord-dark": nordDark,
  "nord-light": nordLight,
  "solarized-dark": solarizedDark,
  "solarized-light": solarizedLight,
};

export const defaultTheme = "light";
